final List<Map<String, String>> countries = [
{"name": "Afghanistan", "flag": "🇦🇫", "code": "+93", "currency": "AFN"},
{"name": "Albania", "flag": "🇦🇱", "code": "+355", "currency": "ALL"},
{"name": "Algeria", "flag": "🇩🇿", "code": "+213", "currency": "DZD"},
{"name": "Andorra", "flag": "🇦🇩", "code": "+376", "currency": "EUR"},
{"name": "Angola", "flag": "🇦🇴", "code": "+244", "currency": "AOA"},
{"name": "Antigua and Barbuda", "flag": "🇦🇬", "code": "+1268", "currency": "XCD"},
{"name": "Argentina", "flag": "🇦🇷", "code": "+54", "currency": "ARS"},
{"name": "Armenia", "flag": "🇦🇲", "code": "+374", "currency": "AMD"},
{"name": "Australia", "flag": "🇦🇺", "code": "+61", "currency": "AUD"},
{"name": "Austria", "flag": "🇦🇹", "code": "+43", "currency": "EUR"},
{"name": "Azerbaijan", "flag": "🇦🇿", "code": "+994", "currency": "AZN"},
{"name": "Bahamas", "flag": "🇧🇸", "code": "+1242", "currency": "BSD"},
{"name": "Bahrain", "flag": "🇧🇭", "code": "+973", "currency": "BHD"},
{"name": "Bangladesh", "flag": "🇧🇩", "code": "+880", "currency": "BDT"},
{"name": "Barbados", "flag": "🇧🇧", "code": "+1246", "currency": "BBD"},
{"name": "Belarus", "flag": "🇧🇾", "code": "+375", "currency": "BYN"},
{"name": "Belgium", "flag": "🇧🇪", "code": "+32", "currency": "EUR"},
{"name": "Belize", "flag": "🇧🇿", "code": "+501", "currency": "BZD"},
{"name": "Benin", "flag": "🇧🇯", "code": "+229", "currency": "XOF"},
{"name": "Bhutan", "flag": "🇧🇹", "code": "+975", "currency": "BTN"},
{"name": "Bolivia", "flag": "🇧🇴", "code": "+591", "currency": "BOB"},
{"name": "Bosnia and Herzegovina", "flag": "🇧🇦", "code": "+387", "currency": "BAM"},
{"name": "Botswana", "flag": "🇧🇼", "code": "+267", "currency": "BWP"},
{"name": "Brazil", "flag": "🇧🇷", "code": "+55", "currency": "BRL"},
{"name": "Brunei", "flag": "🇧🇳", "code": "+673", "currency": "BND"},
{"name": "Bulgaria", "flag": "🇧🇬", "code": "+359", "currency": "BGN"},
{"name": "Burkina Faso", "flag": "🇧🇫", "code": "+226", "currency": "XOF"},
{"name": "Burundi", "flag": "🇧🇮", "code": "+257", "currency": "BIF"},
{"name": "Cabo Verde", "flag": "🇨🇻", "code": "+238", "currency": "CVE"},
{"name": "Cambodia", "flag": "🇰🇭", "code": "+855", "currency": "KHR"},
{"name": "Cameroon", "flag": "🇨🇲", "code": "+237", "currency": "XAF"},
{"name": "Canada", "flag": "🇨🇦", "code": "+1", "currency": "CAD"},
{"name": "Central African Republic", "flag": "🇨🇫", "code": "+236", "currency": "XAF"},
{"name": "Chad", "flag": "🇹🇩", "code": "+235", "currency": "XAF"},
{"name": "Chile", "flag": "🇨🇱", "code": "+56", "currency": "CLP"},
{"name": "China", "flag": "🇨🇳", "code": "+86", "currency": "CNY"},
{"name": "Colombia", "flag": "🇨🇴", "code": "+57", "currency": "COP"},
{"name": "Comoros", "flag": "🇰🇲", "code": "+269", "currency": "KMF"},
{"name": "Congo (Congo-Brazzaville)", "flag": "🇨🇬", "code": "+242", "currency": "XAF"},
{"name": "Congo (DRC)", "flag": "🇨🇩", "code": "+243", "currency": "CDF"},
{"name": "Costa Rica", "flag": "🇨🇷", "code": "+506", "currency": "CRC"},
{"name": "Croatia", "flag": "🇭🇷", "code": "+385", "currency": "EUR"},
{"name": "Cuba", "flag": "🇨🇺", "code": "+53", "currency": "CUP"},
{"name": "Cyprus", "flag": "🇨🇾", "code": "+357", "currency": "EUR"},
{"name": "Czechia", "flag": "🇨🇿", "code": "+420", "currency": "CZK"},
{"name": "Denmark", "flag": "🇩🇰", "code": "+45", "currency": "DKK"},
{"name": "Djibouti", "flag": "🇩🇯", "code": "+253", "currency": "DJF"},
{"name": "Dominica", "flag": "🇩🇲", "code": "+1767", "currency": "XCD"},
{"name": "Dominican Republic", "flag": "🇩🇴", "code": "+1", "currency": "DOP"},
{"name": "Ecuador", "flag": "🇪🇨", "code": "+593", "currency": "USD"},
{"name": "Egypt", "flag": "🇪🇬", "code": "+20", "currency": "EGP"},
{"name": "El Salvador", "flag": "🇸🇻", "code": "+503", "currency": "USD"},
{"name": "Equatorial Guinea", "flag": "🇬🇶", "code": "+240", "currency": "XAF"},
{"name": "Eritrea", "flag": "🇪🇷", "code": "+291", "currency": "ERN"},
{"name": "Estonia", "flag": "🇪🇪", "code": "+372", "currency": "EUR"},
{"name": "Eswatini", "flag": "🇸🇿", "code": "+268", "currency": "SZL"},
{"name": "Ethiopia", "flag": "🇪🇹", "code": "+251", "currency": "ETB"},
{"name": "Fiji", "flag": "🇫🇯", "code": "+679", "currency": "FJD"},
{"name": "Finland", "flag": "🇫🇮", "code": "+358", "currency": "EUR"},
{"name": "France", "flag": "🇫🇷", "code": "+33", "currency": "EUR"},
{"name": "Gabon", "flag": "🇬🇦", "code": "+241", "currency": "XAF"},
{"name": "Gambia", "flag": "🇬🇲", "code": "+220", "currency": "GMD"},
{"name": "Georgia", "flag": "🇬🇪", "code": "+995", "currency": "GEL"},
{"name": "Germany", "flag": "🇩🇪", "code": "+49", "currency": "EUR"},
{"name": "Ghana", "flag": "🇬🇭", "code": "+233", "currency": "GHS"},
{"name": "Greece", "flag": "🇬🇷", "code": "+30", "currency": "EUR"},
{"name": "Grenada", "flag": "🇬🇩", "code": "+1473", "currency": "XCD"},
{"name": "Guatemala", "flag": "🇬🇹", "code": "+502", "currency": "GTQ"},
{"name": "Guinea", "flag": "🇬🇳", "code": "+224", "currency": "GNF"},
{"name": "Guinea-Bissau", "flag": "🇬🇼", "code": "+245", "currency": "XOF"},
{"name": "Guyana", "flag": "🇬🇾", "code": "+592", "currency": "GYD"},
{"name": "Haiti", "flag": "🇭🇹", "code": "+509", "currency": "HTG"},
{"name": "Honduras", "flag": "🇭🇳", "code": "+504", "currency": "HNL"},
{"name": "Hungary", "flag": "🇭🇺", "code": "+36", "currency": "HUF"},
{"name": "Iceland", "flag": "🇮🇸", "code": "+354", "currency": "ISK"},
{"name": "India", "flag": "🇮🇳", "code": "+91", "currency": "INR"},
{"name": "Indonesia", "flag": "🇮🇩", "code": "+62", "currency": "IDR"},
{"name": "Iran", "flag": "🇮🇷", "code": "+98", "currency": "IRR"},
{"name": "Iraq", "flag": "🇮🇶", "code": "+964", "currency": "IQD"},
{"name": "Ireland", "flag": "🇮🇪", "code": "+353", "currency": "EUR"},
{"name": "Israel", "flag": "🇮🇱", "code": "+972", "currency": "ILS"},
{"name": "Italy", "flag": "🇮🇹", "code": "+39", "currency": "EUR"},
{"name": "Jamaica", "flag": "🇯🇲", "code": "+1876", "currency": "JMD"},
{"name": "Japan", "flag": "🇯🇵", "code": "+81", "currency": "JPY"},
{"name": "Jordan", "flag": "🇯🇴", "code": "+962", "currency": "JOD"},
{"name": "Kazakhstan", "flag": "🇰🇿", "code": "+7", "currency": "KZT"},
{"name": "Kenya", "flag": "🇰🇪", "code": "+254", "currency": "KES"},
{"name": "Kiribati", "flag": "🇰🇮", "code": "+686", "currency": "AUD"},
{"name": "Kuwait", "flag": "🇰🇼", "code": "+965", "currency": "KWD"},
{"name": "Kyrgyzstan", "flag": "🇰🇬", "code": "+996", "currency": "KGS"},
{"name": "Laos", "flag": "🇱🇦", "code": "+856", "currency": "LAK"},
{"name": "Latvia", "flag": "🇱🇻", "code": "+371", "currency": "EUR"},
{"name": "Lebanon", "flag": "🇱🇧", "code": "+961", "currency": "LBP"},
{"name": "Lesotho", "flag": "🇱🇸", "code": "+266", "currency": "LSL"},
{"name": "Liberia", "flag": "🇱🇷", "code": "+231", "currency": "LRD"},
{"name": "Libya", "flag": "🇱🇾", "code": "+218", "currency": "LYD"},
{"name": "Liechtenstein", "flag": "🇱🇮", "code": "+423", "currency": "CHF"},
{"name": "Lithuania", "flag": "🇱🇹", "code": "+370", "currency": "EUR"},
{"name": "Luxembourg", "flag": "🇱🇺", "code": "+352", "currency": "EUR"},
{"name": "Madagascar", "flag": "🇲🇬", "code": "+261", "currency": "MGA"},
{"name": "Malawi", "flag": "🇲🇼", "code": "+265", "currency": "MWK"},
{"name": "Malaysia", "flag": "🇲🇾", "code": "+60", "currency": "MYR"},
{"name": "Maldives", "flag": "🇲🇻", "code": "+960", "currency": "MVR"},
{"name": "Mali", "flag": "🇲🇱", "code": "+223", "currency": "XOF"},
{"name": "Malta", "flag": "🇲🇹", "code": "+356", "currency": "EUR"},
{"name": "Marshall Islands", "flag": "🇲🇭", "code": "+692", "currency": "USD"},
{"name": "Mauritania", "flag": "🇲🇷", "code": "+222", "currency": "MRU"},
{"name": "Mauritius", "flag": "🇲🇺", "code": "+230", "currency": "MUR"},
{"name": "Mexico", "flag": "🇲🇽", "code": "+52", "currency": "MXN"},
{"name": "Micronesia", "flag": "🇫🇲", "code": "+691", "currency": "USD"},
{"name": "Moldova", "flag": "🇲🇩", "code": "+373", "currency": "MDL"},
{"name": "Monaco", "flag": "🇲🇨", "code": "+377", "currency": "EUR"},
{"name": "Mongolia", "flag": "🇲🇳", "code": "+976", "currency": "MNT"},
{"name": "Montenegro", "flag": "🇲🇪", "code": "+382", "currency": "EUR"},
{"name": "Morocco", "flag": "🇲🇦", "code": "+212", "currency": "MAD"},
{"name": "Mozambique", "flag": "🇲🇿", "code": "+258", "currency": "MZN"},
{"name": "Myanmar", "flag": "🇲🇲", "code": "+95", "currency": "MMK"},
{"name": "Namibia", "flag": "🇳🇦", "code": "+264", "currency": "NAD"},
{"name": "Nauru", "flag": "🇳🇷", "code": "+674", "currency": "AUD"},
{"name": "Nepal", "flag": "🇳🇵", "code": "+977", "currency": "NPR"},
{"name": "Netherlands", "flag": "🇳🇱", "code": "+31", "currency": "EUR"},
{"name": "New Zealand", "flag": "🇳🇿", "code": "+64", "currency": "NZD"},
{"name": "Nicaragua", "flag": "🇳🇮", "code": "+505", "currency": "NIO"},
{"name": "Niger", "flag": "🇳🇪", "code": "+227", "currency": "XOF"},
{"name": "Nigeria", "flag": "🇳🇬", "code": "+234", "currency": "NGN"},
{"name": "North Korea", "flag": "🇰🇵", "code": "+850", "currency": "KPW"},
{"name": "North Macedonia", "flag": "🇲🇰", "code": "+389", "currency": "MKD"},
{"name": "Norway", "flag": "🇳🇴", "code": "+47", "currency": "NOK"},
{"name": "Oman", "flag": "🇴🇲", "code": "+968", "currency": "OMR"},
{"name": "Pakistan", "flag": "🇵🇰", "code": "+92", "currency": "PKR"},
{"name": "Palau", "flag": "🇵🇼", "code": "+680", "currency": "USD"},
{"name": "Palestine", "flag": "🇵🇸", "code": "+970", "currency": "ILS"},
{"name": "Panama", "flag": "🇵🇦", "code": "+507", "currency": "PAB"},
{"name": "Papua New Guinea", "flag": "🇵🇬", "code": "+675", "currency": "PGK"},
];